server:
  port: 5001
  servlet:
   context-path: /citylist

jwt:
    secret: nagel
    
spring:
  datasource:
    password: admin123
    url: jdbc:mysql://localhost:3306/expatswap
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
